// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.indra.formacion.pr.springroo.basico.model;

import es.indra.formacion.pr.springroo.basico.model.Ordenador;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Ordenador_Roo_Configurable {
    
    declare @type: Ordenador: @Configurable;
    
}
