// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.indra.formacion.pr.springroo.basico.model;

import es.indra.formacion.pr.springroo.basico.model.Ordenador;
import es.indra.formacion.pr.springroo.basico.model.OrdenadorDataOnDemand;
import es.indra.formacion.pr.springroo.basico.model.Persona;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect OrdenadorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrdenadorDataOnDemand: @Component;
    
    private Random OrdenadorDataOnDemand.rnd = new SecureRandom();
    
    private List<Ordenador> OrdenadorDataOnDemand.data;
    
    public Ordenador OrdenadorDataOnDemand.getNewTransientOrdenador(int index) {
        Ordenador obj = new Ordenador();
        setNombre(obj, index);
        setPersona(obj, index);
        setSerial(obj, index);
        return obj;
    }
    
    public void OrdenadorDataOnDemand.setNombre(Ordenador obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void OrdenadorDataOnDemand.setPersona(Ordenador obj, int index) {
        Persona persona = null;
        obj.setPersona(persona);
    }
    
    public void OrdenadorDataOnDemand.setSerial(Ordenador obj, int index) {
        String serial = "serial_" + index;
        obj.setSerial(serial);
    }
    
    public Ordenador OrdenadorDataOnDemand.getSpecificOrdenador(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Ordenador obj = data.get(index);
        Long id = obj.getId();
        return Ordenador.findOrdenador(id);
    }
    
    public Ordenador OrdenadorDataOnDemand.getRandomOrdenador() {
        init();
        Ordenador obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Ordenador.findOrdenador(id);
    }
    
    public boolean OrdenadorDataOnDemand.modifyOrdenador(Ordenador obj) {
        return false;
    }
    
    public void OrdenadorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Ordenador.findOrdenadorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Ordenador' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Ordenador>();
        for (int i = 0; i < 10; i++) {
            Ordenador obj = getNewTransientOrdenador(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
