// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.indra.formacion.pr.springroo.basico.model;

import es.indra.formacion.pr.springroo.basico.model.PersonaIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PersonaIntegrationTest_Roo_Configurable {
    
    declare @type: PersonaIntegrationTest: @Configurable;
    
}
